#!/usr/bin/env python3
"""
Construct a water box using packmol.

This script generates a packmol input file to create a box of water molecules
and optionally runs packmol to generate the coordinate file.
"""

import argparse
import os
import subprocess
import sys


def generate_packmol_input(
    output_pdb="water_box.pdb",
    water_pdb="water.pdb",
    n_molecules=1000,
    box_size=30.0,
    tolerance=2.0,
    seed=-1
):
    """
    Generate a packmol input file for creating a water box.
    
    Parameters:
    -----------
    output_pdb : str
        Output PDB file name for the water box
    water_pdb : str
        Input PDB file containing a single water molecule
    n_molecules : int
        Number of water molecules to pack
    box_size : float
        Size of the cubic box in Angstroms
    tolerance : float
        Minimum distance between atoms in Angstroms
    seed : int
        Random seed for packmol (-1 for random)
    
    Returns:
    --------
    str : The packmol input file content
    """
    packmol_input = f"""#
# Packmol input file for water box generation
# Generated by construct_water_box.py
#

tolerance {tolerance}
filetype pdb
output {output_pdb}
"""
    
    if seed != -1:
        packmol_input += f"seed {seed}\n"
    
    packmol_input += f"""
structure {water_pdb}
  number {n_molecules}
  inside cube 0.0 0.0 0.0 {box_size}
end structure
"""
    
    return packmol_input


def write_packmol_input(input_content, filename="packmol_input.inp"):
    """
    Write the packmol input to a file.
    
    Parameters:
    -----------
    input_content : str
        The packmol input file content
    filename : str
        Output filename for the packmol input
    """
    with open(filename, 'w') as f:
        f.write(input_content)
    print(f"Packmol input file written to: {filename}")


def run_packmol(input_file="packmol_input.inp", packmol_exe="packmol"):
    """
    Run packmol with the given input file.
    
    Parameters:
    -----------
    input_file : str
        Path to the packmol input file
    packmol_exe : str
        Path to the packmol executable
    
    Returns:
    --------
    bool : True if successful, False otherwise
    """
    try:
        # Check if packmol is available
        with open(input_file, 'r') as f:
            result = subprocess.run(
                [packmol_exe],
                stdin=f,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
        
        print("Packmol output:")
        print(result.stdout)
        
        if result.returncode != 0:
            print("Packmol errors:", file=sys.stderr)
            print(result.stderr, file=sys.stderr)
            return False
        
        return True
        
    except FileNotFoundError:
        print(f"Error: {packmol_exe} not found. Please install packmol.", file=sys.stderr)
        print("Packmol input file has been generated. You can run packmol manually:", file=sys.stderr)
        print(f"  packmol < {input_file}", file=sys.stderr)
        return False
    except Exception as e:
        print(f"Error running packmol: {e}", file=sys.stderr)
        return False


def main():
    """Main function to parse arguments and generate water box."""
    parser = argparse.ArgumentParser(
        description="Generate a water box using packmol",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    parser.add_argument(
        "-o", "--output",
        default="water_box.pdb",
        help="Output PDB file for the water box"
    )
    
    parser.add_argument(
        "-w", "--water",
        default="water.pdb",
        help="Input PDB file containing a single water molecule"
    )
    
    parser.add_argument(
        "-n", "--nmol",
        type=int,
        default=1000,
        help="Number of water molecules"
    )
    
    parser.add_argument(
        "-b", "--box",
        type=float,
        default=30.0,
        help="Size of the cubic box in Angstroms"
    )
    
    parser.add_argument(
        "-t", "--tolerance",
        type=float,
        default=2.0,
        help="Minimum distance between atoms in Angstroms"
    )
    
    parser.add_argument(
        "-s", "--seed",
        type=int,
        default=-1,
        help="Random seed for packmol (-1 for random)"
    )
    
    parser.add_argument(
        "-i", "--input",
        default="packmol_input.inp",
        help="Packmol input file name"
    )
    
    parser.add_argument(
        "--no-run",
        action="store_true",
        help="Only generate input file, do not run packmol"
    )
    
    parser.add_argument(
        "--packmol-exe",
        default="packmol",
        help="Path to packmol executable"
    )
    
    args = parser.parse_args()
    
    # Check if water PDB file exists
    if not os.path.exists(args.water):
        print(f"Error: Water molecule file '{args.water}' not found.", file=sys.stderr)
        sys.exit(1)
    
    # Generate packmol input
    print(f"Generating packmol input for {args.nmol} water molecules")
    print(f"Box size: {args.box} Angstroms")
    print(f"Tolerance: {args.tolerance} Angstroms")
    
    input_content = generate_packmol_input(
        output_pdb=args.output,
        water_pdb=args.water,
        n_molecules=args.nmol,
        box_size=args.box,
        tolerance=args.tolerance,
        seed=args.seed
    )
    
    # Write input file
    write_packmol_input(input_content, args.input)
    
    # Run packmol if requested
    if not args.no_run:
        print("\nRunning packmol...")
        success = run_packmol(args.input, args.packmol_exe)
        
        if success:
            print(f"\nWater box successfully generated: {args.output}")
            if os.path.exists(args.output):
                # Count atoms in output file
                with open(args.output, 'r') as f:
                    n_atoms = sum(1 for line in f if line.startswith('HETATM') or line.startswith('ATOM'))
                print(f"Total atoms in water box: {n_atoms}")
        else:
            print("\npackmol input file generated. Run manually with:", file=sys.stderr)
            print(f"  packmol < {args.input}", file=sys.stderr)
            sys.exit(1)
    else:
        print("\npackmol input file generated. Run with:")
        print(f"  packmol < {args.input}")


if __name__ == "__main__":
    main()
